### ISSUE TITLE
[BUG] Bad ownership or modes for directory /data/git/.ssh

### ISSUE THREAD

**Issue by onedr0p** [novumrgi/helm#4] opened 2020-08-05 17:17 UTC
When I try to clone via SSH I get the following error:

```
git clone --verbose ssh://git@git.dude.io:1337/dude/test.git
Cloning into 'test'...
git@git.dude.io: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Gitea logs:

```
[gitea-0 gitea] Authentication refused: bad ownership or modes for directory /data/git/.ssh
[gitea-0 gitea] Connection closed by authenticating user git 10.42.3.1 port 54914 [preauth]
```

To resolve I exec'd into the container

```
$ k exec -it pod/gitea-0 -c gitea -- bash
# chmod 700 /data/git.ssh
```

Now I can clone via ssh!

**Comment by luhahn** [comment] 2020-08-06 07:45
can you show ls -la from that folder before you change it?

**Comment by luhahn** [comment] 2020-08-06 07:50
guess i could use the init container to chmod 700 this folder
But it's weird because gitea should create the folder itself. Could it be a remain from a previous, failed install from where we got the permissions wrong? Or did you have a clean install with clean PVC

**Comment by onedr0p** [comment] 2020-08-06 09:40
This was from a clean install. I think the permissions before I ran the cmd was 

```
drwx------
```

**Comment by luhahn** [comment] 2020-08-06 10:22
That would be odd, because these are the exact permissions that i would expect. And chmod 700 does not change anything there:

```
bash-5.0# ls -la
total 7
drwxr-xr-x    4 git      root             5 Aug  5 13:39 .
drwxrwxrwx    5 root     root             5 Aug  5 13:39 ..
-rw-r--r--    1 git      root           123 Aug  5 13:39 .gitconfig
drwx------    2 git      root             3 Aug  5 13:39 .ssh
drwxr-xr-x    3 git      root             3 Aug  5 13:39 gitea-repositories
bash-5.0# chmod 700 .ssh
bash-5.0# ls -la
total 7
drwxr-xr-x    4 git      root             5 Aug  5 13:39 .
drwxrwxrwx    5 root     root             5 Aug  5 13:39 ..
-rw-r--r--    1 git      root           123 Aug  5 13:39 .gitconfig
drwx------    2 git      root             3 Aug  5 13:39 .ssh
drwxr-xr-x    3 git      root             3 Aug  5 13:39 gitea-repositories
```

**Comment by onedr0p** [comment] 2020-08-06 10:44
From what I'm reading the folder . ssh should be 700. Maybe your aren't seeing this issue because of the way NFS handles permissions?

**Comment by luhahn** [comment] 2020-08-06 10:47
Yeah i wanted to install longhorn later that day to check this issues, I was a little lazy so I asked you if you can show the whole permissions from before the change :D

**Comment by onedr0p** [comment] 2020-08-06 10:49
I don't think it's just longhorn, if you're testing in the cloud any block based like EBS would probably yield similar issues.

**Comment by luhahn** [comment] 2020-08-06 13:08
seems to be some strange behaviour, could not reproduce with longhorn. Closing this for now and reopening if the error reappears

**Closed by luhahn** 2020-08-06 13:08 UTC

**Comment by onedr0p** [comment] 2020-08-06 13:33
agreedm thanks!
