### ISSUE TITLE
Issue with ssh-svc

### ISSUE THREAD

**Issue by onedr0p** [novumrgi/helm#1] opened 2020-08-03 21:04 UTC
Hi, thanks for creating this chart, however I am running into an issue. Here are my helm options:

https://github.com/onedr0p/k3s-gitops/blob/master/deployments/default/gitea/gitea.yaml#L19
https://github.com/onedr0p/k3s-gitops/blob/master/deployments/default/gitea/gitea.txt

and here is the error

```
[helm-operator-55f6946fbc-6djtz] ts=2020-08-03T21:00:07.876484048Z caller=release.go:278 component=release release=gitea targetNamespace=default resource=default:helmrelease/gitea helmVersion=v3 error="installation failed: template: gitea/templates/gitea/ssh-svc.yaml:11:9: executing \"gitea/templates/gitea/ssh-svc.yaml\" at <(.Values.service.ssh.loadBalancerIP) and eq .Values.service.ssh.serviceType \"LoadBalancer\">: can't give argument to non-function .Values.service.ssh.loadBalancerIP" phase=install
```

I am using helm 3

**Comment by luhahn** [comment] 2020-08-05 07:25
Hi this was caused by a false and operator statement, which worked fine on helm 3.0.x but did not in 3.2.4.
Should be fixed by c2185b2228644d48cf70494ed27d97ff4e631183

@onedr0p  Can you check again and confirm, that this works for you?

**Comment by onedr0p** [comment] 2020-08-05 11:47
Looks like I have a caching issue, could you bump the chart version? I'll try to find a way around it on my end.

**Comment by luhahn** [comment] 2020-08-05 11:52
Done

**Comment by onedr0p** [comment] 2020-08-05 12:08
Great, another odd issue I am having, not sure if it's config related...

```
gitea-0                                  0/1     Init:Error   5          3m38s
```

```
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Warning  FailedScheduling        <unknown>              default-scheduler        running "VolumeBinding" filter plugin for pod "gitea-0": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling        <unknown>              default-scheduler        running "VolumeBinding" filter plugin for pod "gitea-0": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               <unknown>              default-scheduler        Successfully assigned default/gitea-0 to k3s-worker-c
  Warning  FailedMount             3m53s                  kubelet, k3s-worker-c    MountVolume.SetUp failed for volume "config" : failed to sync configmap cache: timed out waiting for the condition
  Normal   SuccessfulAttachVolume  3m48s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-c8acb806-3b6f-46ad-9f51-fc54bdf339f8"
  Warning  FailedMount             3m44s (x3 over 3m46s)  kubelet, k3s-worker-c    MountVolume.SetUp failed for volume "pvc-c8acb806-3b6f-46ad-9f51-fc54bdf339f8" : rpc error: code = InvalidArgument desc = There is no block device frontend for volume pvc-c8acb806-3b6f-46ad-9f51-fc54bdf339f8
```

**Comment by luhahn** [comment] 2020-08-05 12:13
that is indeed odd. The PVC are there and named correctly ...

I'll have a look

**Comment by onedr0p** [comment] 2020-08-05 12:18
Maybe it's something related on my end. I am using SealedSecrets and it looks like the configmap is not generating correctly. I only see the default values.

**Comment by luhahn** [comment] 2020-08-05 12:18
For what I found it seems somehow related to longhorn. To be honest I havent tested on longhorn yet

**Comment by onedr0p** [comment] 2020-08-05 12:20
Hm. I can't believe that would be the issue. All my other deployments work fine with it.  I am noticing the configmap is not being updated with my values.

**Comment by luhahn** [comment] 2020-08-05 12:24
are the values still the same as in: https://github.com/onedr0p/k3s-gitops/blob/master/deployments/default/gitea/gitea.yaml#L19?
if so, the config values should be in 
gitea:
 config:
 repository:
... etc

**Comment by onedr0p** [comment] 2020-08-05 12:30
Yep lines 19 thru the end get passed to the helm-operator

**Comment by luhahn** [comment] 2020-08-05 12:31
And I found this one https://github.com/longhorn/longhorn/issues/1465 that's why i thought it might be longhorn related, since it is the exact same message you're receiving

**Comment by onedr0p** [comment] 2020-08-05 12:33
Good catch, I'll investigate more...

**Comment by luhahn** [comment] 2020-08-05 12:34
for the config map, it should be populated correctly if you use the values like this.
```yaml
gitea:
   config:
      appName: "Devin's wonderful Gitea"
      adminUser: "devin"
    respository:
      defaultPrivate: true
    server:
      http: 
        externalPort: 443
      ssh:
        externalPort: 1337
    database:
      builtIn:
        postgresql:
          enabled: true
    admin:
      disableRegularOrgCreation: true
    security:
      minPasswordLength: 12
    service:
      disableRegistration: true
```
      requireSigninView: true

**Comment by luhahn** [comment] 2020-08-05 14:32
Fixed :)

**Comment by onedr0p** [comment] 2020-08-05 14:33
All good, thanks!

**Closed by luhahn** 2020-08-05 14:32 UTC
